# Generated by Django 6.0.3 on 2026-04-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='initial_comment',
        ),
    ]
