# Generated by Django 6.0.3 on 2026-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyteller',
            options={'verbose_name': 'Разказвач', 'verbose_name_plural': 'Разказвачи'},
        ),
        migrations.AddField(
            model_name='storyteller',
            name='location',
            field=models.CharField(blank=True, help_text='От коя част на света е историята Ви?', max_length=100, verbose_name='Регион/Град'),
        ),
        migrations.AddField(
            model_name='storyteller',
            name='website',
            field=models.URLField(blank=True, verbose_name='Личен сайт/Блог'),
        ),
        migrations.AlterField(
            model_name='storyteller',
            name='bio',
            field=models.TextField(blank=True, help_text='Разкажете накратко за Вашия кулинарен или разказвачески опит.', max_length=500, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='storyteller',
            name='nickname',
            field=models.CharField(blank=True, help_text='Името, с което ще се подписвате под историите.', max_length=50, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='storyteller',
            name='rank',
            field=models.CharField(default='Лозова сърмичка', help_text='Вашият статус в общността на Sarma Box Tales', max_length=30, verbose_name='Ранг'),
        ),
    ]
