# Generated by Django 6.0.3 on 2026-04-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_storyteller_options_storyteller_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyteller',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
