# Generated by Django 6.0.3 on 2026-04-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_storyteller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyteller',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
